### ISSUE TITLE
Error during OtoroshiVerifierJob 

### ISSUE THREAD

**Issue by sadmin91** [MAIF/daikoku#768]
**Describe the bug**
When I update an API plan on Daikoku an asynchronous job is run on Daikoku to update Otoroshi data.
During this job execution, this error is loggued on Daikoku log file:

> OtoroshiVerifierJob - Verifying sync between daikoku and otoroshi
> [error] application - JsResultException(errors:List((,List(JsonValidationError(List(null is not an object),List())))))
> play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List(null is not an object),List())))))
> 	at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
> 	at play.api.libs.json.JsError.fold(JsResult.scala:66)
> 	at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
>	at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
> 	at play.api.libs.json.JsUndefined.as(JsLookup.scala:193)
> 	at fr.maif.otoroshi.daikoku.domain.json$$anon$88.$anonfun$reads$312(json.scala:2892)
> 	at scala.util.Try$.apply(Try.scala:210)
> 	at fr.maif.otoroshi.daikoku.domain.json$$anon$88.reads(json.scala:2890)
> 	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
> 	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
> [error] application - JsResultException(errors:List((,List(JsonValidationError(List(null is not an object),List())))))

Despite this error, Otoroshi data is updated.

**To Reproduce**
1. On Daikoku try to update an usage plan
2. See error on Daikoku log file

**Expected behavior**
No error loggued on Daikoku log file.

**Additional context**
- Daikoku version: 16.3.6
- Otoroshi version: 16.19.0

**Comment by quentinovega** [comment]
I can't reproduce your issue. Could you please post the entire stack trace ?

**Comment by sadmin91** [comment]
I don't have any additional information on log file.

**Comment by quentinovega** [comment]
Job has been rewrite and we can't reproduce
